#!/usr/bin/env python3
"""
This script converts the SBOM file generated by Syft tool from docker images into csv format.
"""
import csv
import json
import sys

with open(sys.argv[1] + ".json") as json_file:
    jsondata = json.load(json_file)

data_file = open(sys.argv[1] + ".csv", "a", newline="")
csv_writer = csv.writer(data_file)

count = 0
for data in jsondata:
    if count == 0:
        header = data.keys()
        csv_writer.writerow(header)
        count += 1
    csv_writer.writerow(data.values())

data_file.close()
