# FRPC MQTT Client

serverAddr = "FRP_HOST"
serverPort = 7000
auth.method = "token"
auth.token = "FRP_TOKEN"

[[proxies]]
name = "SERVICE_NAME-tcpFRP_NAME_SUFFIX"
type = "tcp"
localIP = "INTERNAL_HOST"
localPort = INTERNAL_PORT
remotePort = FRP_EXTERNAL_PORT
