---
name: Execute System Tests

on:
  workflow_call:
    inputs:
      lc-run-id:
        required: true
        type: string
        description: |
          Workflow run id from the build python wheel job,
          used for downloading the compiled wheel artifact
      lc-wheel-artifact:
        required: false
        type: string
        default: "python-wheel"
        description: |
          Name of the wheel artifact compiled by the build python wheel job
      v17ref:
        required: false
        type: string
        default: hiiragi
        description: Branch reference for CamFW v1.7
      v15ref:
        required: false
        type: string
        default: t3p_v1x
        description: Branch reference for CamFW v1.5

jobs:

  build-v1_4:
    name: FW v1.4.3
    uses: ./.github/workflows/type3-fw-build.yaml
    with:
      t3ref: 'vD7.00.T0'
    secrets:
      sss-user: ${{ secrets.TEMPORARY_PAT_USER }}
      sss-token: ${{ secrets.TEMPORARY_PAT_TOKEN }}

  build-v1_5:
    name: FW v1.5.x
    uses: ./.github/workflows/type3-fw-build.yaml
    with:
      t3ref: 't3p_v1x'
    secrets:
      sss-user: ${{ secrets.TEMPORARY_PAT_USER }}
      sss-token: ${{ secrets.TEMPORARY_PAT_TOKEN }}

  main-tests:
    name: Main tests
    uses: ./.github/workflows/system-tests-main.yaml
    needs:
      - build-v1_5
    secrets: inherit
    with:
      v15ref: 't3p_v1x'
      fw-run-id: ${{ github.run_id }}
      fw-artifact: ${{ needs.build-v1_5.outputs.artifact }}
      lc-run-id: ${{ inputs.lc-run-id }}
      lc-wheel-artifact: ${{ inputs.lc-wheel-artifact }}

  ota-v1_4-test:
    name: OTA v1.4 test
    uses: ./.github/workflows/system-tests-ota-v1.4.yaml
    needs:
      - build-v1_4
      - build-v1_5
      # There seems to be an issue with having two concurrent
      # MQTT brokers.
      - main-tests
    secrets: inherit
    with:
      v15ref: 't3p_v1x'
      fw-run-id: ${{ github.run_id }}
      fw-v1_4-artifact: ${{ needs.build-v1_4.outputs.artifact }}
      fw-v1_5-artifact: ${{ needs.build-v1_5.outputs.artifact }}
      lc-run-id: ${{ inputs.lc-run-id }}
      lc-wheel-artifact: ${{ inputs.lc-wheel-artifact }}
