---
name: generate-oss-license-report

on:
  workflow_dispatch:
  pull_request:

env:
  PYTHON_VERSION: '3.11'

jobs:
  generate-oss-license-report:
    runs-on: [self-hosted, X64]
    container: ubuntu:22.04
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install requirements
        run: |
          apt-get update && apt-get install -y wget curl software-properties-common
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Docker Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./scripts/Dockerfile
          push: true
          tags: localhost:5000/wedge-cli-image:latest
      - name: Generate SBOM report for wedge-cli container
        uses: anchore/sbom-action@v0
        with:
          image: localhost:5000/wedge-cli-image:latest
          artifact-name: wedge-cli-container-sbom.json
          output-file: wedge-cli-container-sbom.json
          format: json
          upload-artifact: true
      - name: Generate CSV report
        run: |
          mkdir target
          apt-get update && apt-get install -y jq
          cat wedge-cli-container-sbom.json | jq '.artifacts | .[] | {Name: .name, Version: .version, License: .licenses[0].value} ' | jq -s > target/syft-wedge-cli.json
          python scripts/sbom2csv.py target/syft-wedge-cli
          cat target/syft-wedge-cli.csv | sort --unique --ignore-case > target/wedge-cli-container-sbom-report.csv
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: wedge-cli-container-sbom-report.csv
          retention-days: 21
          path: target/wedge-cli-container-sbom-report.csv
