name: generate-windows-installer

on:
  workflow_dispatch:
  push:
    branches:
      - main
  # TODO: remove
  pull_request:

env:
  KIVY_GL_BACKEND: 'angle_sdl2'

jobs:
  win-installer-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python3 -m venv .venv
          .venv/Scripts/activate
          pip3 install wedge-cli/
          pip3 install pyinstaller==6.3.0
          pip3 uninstall -y -r oss/uninstall.txt

      - name: Create Executable by PyInstaller
        run: |
          .venv/Scripts/activate
          pyinstaller --clean --noconfirm --distpath ./wedge-cli --workpath ./wedge-cli ./wedge-cli/pyinstaller.spec

      - name: Download mosquitto installer
        run: curl -o wedge-cli/mosquitto-2.0.18-install-windows-x64.exe https://mosquitto.org/files/binary/win64/mosquitto-2.0.18-install-windows-x64.exe

      - name: Build the Inno Setup Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.4
        with:
          path: ./wedge-cli/inno-setup.iss
          options: /O+

      - name: Upload the Inno Setup Installer
        uses: actions/upload-artifact@v4
        with:
          name: offline-tool-windows-installer
          path: ./wedge-cli/Output/offline-tool-setup.exe
