name: windows-installer

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      ARTIFACT_NAME: windows-installer
    outputs:
      artifact: ${{ env.ARTIFACT_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build the Inno Setup Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.4
        with:
          path: ./inno-setup.iss
          options: /O+

      - name: Upload the Inno Setup Installer
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./Output/offline-tool-setup.exe
